### ISSUE TITLE
Unable to join bedrock portal worlds after the 1.21.20 update

### ISSUE THREAD

**Issue by Hermet1c** [LucienHH/bedrock-portal#10] opened 2024-08-20 20:00 UTC
when joining a bedrock portal world, it displays `Connecting to multiplayer game` followed by a disconnect screen with a `Internet connection issue` error
![ApplicationFrameHost_vQWWoKmCBp](https://github.com/user-attachments/assets/41283ff4-674d-410f-b46c-4eb7dc404022)

**Comment by LucienHH** [comment] 2024-08-21 22:34
Dupe of #9 . Will leave a comment there addressing this issue. Thanks!

**Closed as completed by LucienHH** 2024-08-21 22:34 UTC
